keys:
  - &pgp 8D1DC1ED8C610F59B049CBF2495241EAF24EB05D
  - &glados age1w2mp6ut4m03rrlymz0j6f32e5wjwnqjz8rjcxd48xvay5sr624rq0mz9gt
creation_rules:
  - path_regex: users/secrets.ya?ml$
    key_groups:
    -
      age:
        - *glados
      pgp:
        - *pgp
  - path_regex: hosts/GLaDOS/secrets.ya?ml$
    key_groups:
    -
      age:
        - *glados
      pgp:
        - *pgp
  - path_regex: hosts/Wheatley/secrets.ya?ml$
    key_groups:
    -
      pgp:
        - *pgp
